import {
  BellIcon,
  CalendarIcon,
  ClockIcon,
  CogIcon,
  UserIcon,
  CreditCardIcon,
  DocumentAddIcon,
  DocumentIcon,
  DocumentReportIcon,
  HomeIcon,
  MenuAlt1Icon,
  QuestionMarkCircleIcon,
  ReceiptRefundIcon,
  ScaleIcon,
  ShieldCheckIcon,
  TruckIcon,
  UserGroupIcon,
  LogoutIcon,
  ViewGridIcon,
  ViewListIcon,
  MailIcon,
  XIcon,
  ArchiveIcon,
} from "@heroicons/react/outline";
import {
  CashIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  OfficeBuildingIcon,
  SearchIcon,
  MailIcon as MailIconSolid,
  PhoneIcon,
  PencilIcon,
  TrashIcon,
} from "@heroicons/react/solid";

export default {
  archive: ArchiveIcon,
  bell: BellIcon,
  calendar: CalendarIcon,
  cash: CashIcon,
  checkCircle: CheckCircleIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  clock: ClockIcon,
  cog: CogIcon,
  creditCard: CreditCardIcon,
  document: DocumentIcon,
  documentAdd: DocumentAddIcon,
  documentReport: DocumentReportIcon,
  home: HomeIcon,
  logout: LogoutIcon,
  mail: MailIcon,
  mailSolid: MailIconSolid,
  menu: MenuAlt1Icon,
  officeBuilding: OfficeBuildingIcon,
  questionMark: QuestionMarkCircleIcon,
  receiptRefund: ReceiptRefundIcon,
  scale: ScaleIcon,
  pencil: PencilIcon,
  trash: TrashIcon,
  phone: PhoneIcon,
  search: SearchIcon,
  shieldCheck: ShieldCheckIcon,
  truck: TruckIcon,
  user: UserIcon,
  userGroup: UserGroupIcon,
  viewGrid: ViewGridIcon,
  viewList: ViewListIcon,
  x: XIcon,
};
